Development
SternLabTAU/AccuNGS pull request #3
Opened 2020-12-06 13:19 UTC by nitsandaniel1

Added an alert when the folder is full

2020-12-06 13:58 UTC, nitsandaniel1 commented
also added env_requirements.txt

2020-12-06 14:40 UTC, theitush requested changes

2020-12-06 14:40 UTC, theitush commented on env_requirements.txt
> +https://repo.anaconda.com/pkgs/main/win-64/git-2.23.0-h6bb4b03_0.conda
how would you install the requirements using this file?
could you add instructions to the README ?

2020-12-06 14:40 UTC, theitush commented on runner.py
> +    if os.path.exists(output_dir): # the output folder must be empty
note bellow that output_dir can be None which would result in an error here...
So this check should happen after assigning output_dir (a few lines down)

2020-12-06 14:40 UTC, theitush commented on runner.py
> +    if os.path.exists(output_dir): # the output folder must be empty
also the comment is redundant

2020-12-06 14:40 UTC, theitush commented on runner.py
> +            raise Exception("The output folder is not empty. Empty it or choose a different name.")
should stick to existing variable names and be more concise so something like: "output_dir must be a path to a new or empty directory"

2020-12-07 08:32 UTC, theitush commented on README.md
> +In order to install the environment: conda create --file requirements.txt name_of_new_environment
great.
Only that it's env_requirements.txt.. please be consistent..!

2020-12-07 11:02 UTC, theitush commented on runner.py
> +    if os.path.exists(output_dir): # the output folder must be empty
redundant comment

2020-12-07 11:05 UTC, theitush commented on runner.py
> +            raise Exception("The output folder is not empty. Empty it or choose a different name.")
please maintain consistency in variable names - "output folder" should be "output_dir".
text is also not clear enough.
Recommend changing to something like: "output_dir must be path to a new or empty directory!"

2020-12-07 11:26 UTC, theitush commented on env_requirements.txt
> +https://repo.anaconda.com/pkgs/main/win-64/git-2.23.0-h6bb4b03_0.conda
This file should be removed.

2020-12-07 11:34 UTC, theitush approved these changes
Mazal Tov!

2020-12-07 11:34 UTC, merged